package com.uzb7.exchangerates.ui.fragment

import android.os.Bundle
import android.util.Log
import android.view.View
import android.widget.AdapterView
import android.widget.Toast
import androidx.fragment.app.Fragment
import androidx.recyclerview.widget.LinearLayoutManager
import com.uzb7.exchangerates.R
import com.uzb7.exchangerates.adapter.RatesRecyclerView
import com.uzb7.exchangerates.adapter.SpinnerRatesAdapter
import com.uzb7.exchangerates.data.remote.ApiClient
import com.uzb7.exchangerates.databinding.FragmentRatesBinding
import com.uzb7.exchangerates.model.Symboles
import com.uzb7.moviedb.utils.viewBinding
import retrofit2.Call
import retrofit2.Callback
import com.uzb7.exchangerates.model.Rates
import retrofit2.Response

@Suppress("CAST_NEVER_SUCCEEDS")
class RatesFragment : Fragment(R.layout.fragment_rates) {
    private val binding by viewBinding { FragmentRatesBinding.bind(it) }
    lateinit var list:ArrayList<Symboles>
    lateinit var adapterCourse:RatesRecyclerView
    var flagList=ArrayList<Symboles>()
    var courseList=ArrayList<Double>()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        initViews()
    }

    private fun initViews() {
        binding.apply {
            list=listSniper()
            val adapter = SpinnerRatesAdapter(requireContext(),list)
            spinnerRates.adapter = adapter
            spinnerRates.onItemSelectedListener=object :AdapterView.OnItemSelectedListener{
                override fun onItemSelected(
                    parent: AdapterView<*>?,
                    view: View?,
                    position: Int,
                    id: Long
                ) {
                    Toast.makeText(requireContext(), list[position].abbr, Toast.LENGTH_SHORT).show()
                    loadCurses()
                }

                override fun onNothingSelected(parent: AdapterView<*>?) {
                }
            }

        }
    }

    private fun loadCurses() {
        ApiClient.apiService.getLatestCourses("UZS").enqueue(object :Callback<com.uzb7.exchangerates.model.Courses>{
            override fun onResponse(
                call: Call<com.uzb7.exchangerates.model.Courses>,
                response: Response<com.uzb7.exchangerates.model.Courses>
            ) {
                if (response.isSuccessful){
                    Log.d("AAAAAAA", "onResponse1: ${response.body()}")
                    binding.tv.text=response.body().toString()
                    loadCourse(response.body()?.rates)
                    adapterCourse=RatesRecyclerView(flagList,courseList)
                    binding.rvRates.adapter=adapterCourse
                    binding.rvRates.layoutManager=LinearLayoutManager(requireContext(),LinearLayoutManager.VERTICAL,false)
                } else{
                    Log.d("AAAAAAA", "onResponse2: ${response.errorBody()}")
                }
            }

            override fun onFailure(
                call: Call<com.uzb7.exchangerates.model.Courses>,
                t: Throwable
            ) {
                Log.d("AAAAAAA", "onFailure: ${t.localizedMessage}")
            }

        })
    }

    private fun loadCourse(rates: Rates?) {
        courseList.add(rates?.aED!!.toDouble())
        courseList.add(rates.aFN!! as Double)
        courseList.add(rates.aLL!! as Double)
        courseList.add(rates.aMD!! as Double)
        courseList.add(rates.aNG!! as Double)
        courseList.add(rates.aOA!! as Double)
        courseList.add(rates.aRS!! as Double)
        courseList.add(rates.aUD!! as Double)
        courseList.add(rates.aWG!! as Double)
        courseList.add(rates.aZN!! as Double)
        courseList.add(rates.bAM!! as Double)
        courseList.add(rates.bBD!! as Double)
        courseList.add(rates.bDT!! as Double)
        courseList.add(rates.bGN!! as Double)
        courseList.add(rates.bHD!! as Double)
        courseList.add(rates.bIF!! as Double)
        courseList.add(rates.bMD!! as Double)
        courseList.add(rates.bND!! as Double)
        courseList.add(rates.bOB!! as Double)
        courseList.add(rates.bRL!! as Double)
        courseList.add(rates.bSD!! as Double)
        courseList.add(rates.bTC!! as Double)
        courseList.add(rates.bTN!! as Double)
        courseList.add(rates.bWP!! as Double)
        courseList.add(rates.bYN!! as Double)
        courseList.add(rates.bYR!! as Double)
        courseList.add(rates.bZD!! as Double)
        courseList.add(rates.cAD!! as Double)
        courseList.add(rates.cDF!! as Double)
        courseList.add(rates.cHF!! as Double)
        courseList.add(rates.cLF!! as Double)
        courseList.add(rates.cLP!! as Double)
        courseList.add(rates.cNY!! as Double)
        courseList.add(rates.cOP!! as Double)
        courseList.add(rates.cRC!! as Double)
        courseList.add(rates.cUC!! as Double)
        courseList.add(rates.cVE!! as Double)
        courseList.add(rates.cZK!! as Double)
        courseList.add(rates.dJF!! as Double)
        courseList.add(rates.dKK!! as Double)
        courseList.add(rates.dOP!! as Double)
        courseList.add(rates.dZD!! as Double)
        courseList.add(rates.eGP!! as Double)
        courseList.add(rates.eRN!! as Double)
        courseList.add(rates.eTB!! as Double)
        courseList.add(rates.eUR!! as Double)
        courseList.add(rates.fJD!! as Double)
        courseList.add(rates.fKP!! as Double)
        courseList.add(rates.gBP!! as Double)
        courseList.add(rates.gEL!! as Double)
        courseList.add(rates.gGP!! as Double)
        courseList.add(rates.gHS!! as Double)
        courseList.add(rates.gIP!! as Double)
        courseList.add(rates.gMD!! as Double)
        courseList.add(rates.gNF!! as Double)
        courseList.add(rates.gTQ!! as Double)
        courseList.add(rates.gYD!! as Double)
        courseList.add(rates.hKD!! as Double)
        courseList.add(rates.hNL!! as Double)
        courseList.add(rates.hRK!! as Double)
        courseList.add(rates.hTG!! as Double)
        courseList.add(rates.hUF!! as Double)
        courseList.add(rates.iDR!! as Double)
        courseList.add(rates.iLS!! as Double)
        courseList.add(rates.iMP!! as Double)
        courseList.add(rates.iNR!! as Double)
        courseList.add(rates.iQD!! as Double)
        courseList.add(rates.iRR!! as Double)
        courseList.add(rates.iSK!! as Double)
        courseList.add(rates.jEP!! as Double)
        courseList.add(rates.jMD!! as Double)
        courseList.add(rates.jOD!! as Double)
        courseList.add(rates.jPY!! as Double)
        courseList.add(rates.kES!! as Double)
        courseList.add(rates.kGS!! as Double)
        courseList.add(rates.kHR!! as Double)
        courseList.add(rates.kMF!! as Double)
        courseList.add(rates.kPW!! as Double)
        courseList.add(rates.kRW!! as Double)
        courseList.add(rates.kWD!! as Double)
        courseList.add(rates.kYD!! as Double)
        courseList.add(rates.kZT!! as Double)
        courseList.add(rates.lAK!! as Double)
        courseList.add(rates.lBP!! as Double)
        courseList.add(rates.lKR!! as Double)
        courseList.add(rates.lRD!! as Double)
        courseList.add(rates.lSL!! as Double)
        courseList.add(rates.lTL!! as Double)
        courseList.add(rates.lVL!! as Double)
        courseList.add(rates.lYD!! as Double)
        courseList.add(rates.mAD!! as Double)
        courseList.add(rates.mDL!! as Double)
        courseList.add(rates.mGA!! as Double)
        courseList.add(rates.mKD!! as Double)
        courseList.add(rates.mMK!! as Double)
        courseList.add(rates.mNT!! as Double)
        courseList.add(rates.mOP!! as Double)
        courseList.add(rates.mRO!! as Double)
        courseList.add(rates.mUR!! as Double)
        courseList.add(rates.mVR!! as Double)
        courseList.add(rates.mWK!! as Double)
        courseList.add(rates.mXN!! as Double)
        courseList.add(rates.mYR!! as Double)
        courseList.add(rates.mZN!! as Double)
        courseList.add(rates.nAD!! as Double)
        courseList.add(rates.nGN!! as Double)
        courseList.add(rates.nIO!! as Double)
        courseList.add(rates.nOK!! as Double)
        courseList.add(rates.nPR!! as Double)
        courseList.add(rates.nZD!! as Double)
        courseList.add(rates.oMR!! as Double)
        courseList.add(rates.pAB!! as Double)
        courseList.add(rates.pEN!! as Double)
        courseList.add(rates.pGK!! as Double)
        courseList.add(rates.pHP!! as Double)
        courseList.add(rates.pKR!! as Double)
        courseList.add(rates.pLN!! as Double)
        courseList.add(rates.pYG!! as Double)
        courseList.add(rates.qAR!! as Double)
        courseList.add(rates.rON!! as Double)
        courseList.add(rates.rSD!! as Double)
        courseList.add(rates.rUB!! as Double)
        courseList.add(rates.rWF!! as Double)
        courseList.add(rates.sAR!! as Double)
        courseList.add(rates.sBD!! as Double)
        courseList.add(rates.sCR!! as Double)
        courseList.add(rates.sDG!! as Double)
        courseList.add(rates.sEK!! as Double)
        courseList.add(rates.sGD!! as Double)
        courseList.add(rates.sHP!! as Double)
        courseList.add(rates.sLE!! as Double)
        courseList.add(rates.sLL!! as Double)
        courseList.add(rates.sOS!! as Double)
        courseList.add(rates.sRD!! as Double)
        courseList.add(rates.sTD!! as Double)
        courseList.add(rates.sVC!! as Double)
        courseList.add(rates.sYP!! as Double)
        courseList.add(rates.sZL!! as Double)
        courseList.add(rates.tHB!! as Double)
        courseList.add(rates.tJS!! as Double)
        courseList.add(rates.tMT!! as Double)
        courseList.add(rates.tND!! as Double)
        courseList.add(rates.tOP!! as Double)
        courseList.add(rates.tRY!! as Double)
        courseList.add(rates.tTD!! as Double)
        courseList.add(rates.tWD!! as Double)
        courseList.add(rates.tZS!! as Double)
        courseList.add(rates.uAH!! as Double)
        courseList.add(rates.uGX!! as Double)
        courseList.add(rates.uSD!! as Double)
        courseList.add(rates.uYU!! as Double)
        courseList.add(rates.uZS!! as Double)
        courseList.add(rates.vEF!! as Double)
        courseList.add(rates.vES!! as Double)
        courseList.add(rates.vND!! as Double)
        courseList.add(rates.vUV!! as Double)
        courseList.add(rates.wST!! as Double)
        courseList.add(rates.xAF!! as Double)
        courseList.add(rates.xAG!! as Double)
        courseList.add(rates.xAU!! as Double)
        courseList.add(rates.xCD!! as Double)
        courseList.add(rates.xDR!! as Double)
        courseList.add(rates.xOF!! as Double)
        courseList.add(rates.xPF!! as Double)
        courseList.add(rates.xPF!! as Double)
        courseList.add(rates.yER!! as Double)
        courseList.add(rates.zAR!! as Double)
        courseList.add(rates.zMK!! as Double)
        courseList.add(rates.zMW!! as Double)
        courseList.add(rates.zWL!! as Double)
    }
    fun listSniper():ArrayList<Symboles>{
        val symboles=ArrayList<Symboles>()
        symboles.add(Symboles("AED","United Arab Emirates Dirham"))
        symboles.add(Symboles("AFN", "Afghan Afghani"))
        symboles.add(Symboles("ALL", "Albanian Lek"))
        symboles.add(Symboles("AMD", "Armenian Dram"))
        symboles.add(Symboles("ANG", "Netherlands Antillean Guilder"))
        symboles.add(Symboles("AOA", "Angolan Kwanza"))
        symboles.add(Symboles("ARS", "Argentine Peso"))
        symboles.add(Symboles("AUD", "Australian Dollar"))
        symboles.add(Symboles("AWG", "Aruban Florin"))
        symboles.add(Symboles("AZN", "Azerbaijani Manat"))
        symboles.add(Symboles("BAM", "Bosnia-Herzegovina Convertible Mark"))
        symboles.add(Symboles("BBD", "Barbadian Dollar"))
        symboles.add(Symboles("BDT", "Bangladeshi Taka"))
        symboles.add(Symboles("BGN", "Bulgarian Lev"))
        symboles.add(Symboles("BHD", "Bahraini Dinar"))
        symboles.add(Symboles("BIF", "Burundian Franc"))
        symboles.add(Symboles("BMD", "Bermudan Dollar"))
        symboles.add(Symboles("BND", "Brunei Dollar"))
        symboles.add(Symboles("BOB", "Bolivian Boliviano"))
        symboles.add(Symboles("BRL", "Brazilian Real"))
        symboles.add(Symboles("BSD", "Bahamian Dollar"))
        symboles.add(Symboles("BTC", "Bitcoin"))
        symboles.add(Symboles("BTN", "Bhutanese Ngultrum"))
        symboles.add(Symboles("BWP", "Botswanan Pula"))
        symboles.add(Symboles("BYN", "New Belarusian Ruble"))
        symboles.add(Symboles("BYR", "Belarusian Ruble"))
        symboles.add(Symboles("BZD", "Belize Dollar"))
        symboles.add(Symboles("CAD", "Canadian Dollar"))
        symboles.add(Symboles("CDF", "Congolese Franc"))
        symboles.add(Symboles("CHF", "Swiss Franc"))
        symboles.add(Symboles("CLF", "Chilean Unit of Account (UF)"))
        symboles.add(Symboles("CLP", "Chilean Peso"))
        symboles.add(Symboles("CNY", "Chinese Yuan"))
        symboles.add(Symboles("COP", "Colombian Peso"))
        symboles.add(Symboles("CRC", "Costa Rican Colón"))
        symboles.add(Symboles("CUC", "Cuban Convertible Peso"))
        symboles.add(Symboles("CUP", "Cuban Peso"))
        symboles.add(Symboles("CVE", "Cape Verdean Escudo"))
        symboles.add(Symboles("CZK", "Czech Republic Koruna"))
        symboles.add(Symboles("DJF", "Djiboutian Franc"))
        symboles.add(Symboles("DKK", "Danish Krone"))
        symboles.add(Symboles("DOP", "Dominican Peso"))
        symboles.add(Symboles("DZD", "Algerian Dinar"))
        symboles.add(Symboles("EGP", "Egyptian Pound"))
        symboles.add(Symboles("ERN", "Eritrean Nakfa"))
        symboles.add(Symboles("ETB", "Ethiopian Birr"))
        symboles.add(Symboles("EUR", "Euro"))
        symboles.add(Symboles("FJD", "Fijian Dollar"))
        symboles.add(Symboles("FKP", "Falkland Islands Pound"))
        symboles.add(Symboles("GBP", "British Pound Sterling"))
        symboles.add(Symboles("GEL", "Georgian Lari"))
        symboles.add(Symboles("GGP", "Guernsey Pound"))
        symboles.add(Symboles("GHS", "Ghanaian Cedi"))
        symboles.add(Symboles("GIP", "Gibraltar Pound"))
        symboles.add(Symboles("GMD", "Gambian Dalasi"))
        symboles.add(Symboles("GNF", "Guinean Franc"))
        symboles.add(Symboles("GTQ", "Guatemalan Quetzal"))
        symboles.add(Symboles("GYD", "Guyanaese Dollar"))
        symboles.add(Symboles("HKD", "Hong Kong Dollar"))
        symboles.add(Symboles("HNL", "Honduran Lempira"))
        symboles.add(Symboles("HRK", "Croatian Kuna"))
        symboles.add(Symboles("HTG", "Haitian Gourde"))
        symboles.add(Symboles("HUF", "Hungarian Forint"))
        symboles.add(Symboles("IDR", "Indonesian Rupiah"))
        symboles.add(Symboles("ILS", "Israeli New Sheqel"))
        symboles.add(Symboles("IMP", "Manx pound"))
        symboles.add(Symboles("INR", "Indian Rupee"))
        symboles.add(Symboles("IQD", "Iraqi Dinar"))
        symboles.add(Symboles("IRR", "Iranian Rial"))
        symboles.add(Symboles("ISK", "Icelandic Króna"))
        symboles.add(Symboles("JEP", "Jersey Pound"))
        symboles.add(Symboles("JMD", "Jamaican Dollar"))
        symboles.add(Symboles("JOD", "Jordanian Dinar"))
        symboles.add(Symboles("JPY", "Japanese Yen"))
        symboles.add(Symboles("KES", "Kenyan Shilling"))
        symboles.add(Symboles("KGS", "Kyrgystani Som"))
        symboles.add(Symboles("KHR", "Cambodian Riel"))
        symboles.add(Symboles("KMF", "Comorian Franc"))
        symboles.add(Symboles("KPW", "North Korean Won"))
        symboles.add(Symboles("KRW", "South Korean Won"))
        symboles.add(Symboles("KWD", "Kuwaiti Dinar"))
        symboles.add(Symboles("KYD", "Cayman Islands Dollar"))
        symboles.add(Symboles("KZT", "Kazakhstani Tenge"))
        symboles.add(Symboles("LAK", "Laotian Kip"))
        symboles.add(Symboles("LBP", "Lebanese Pound"))
        symboles.add(Symboles("LKR", "Sri Lankan Rupee"))
        symboles.add(Symboles("LRD", "Liberian Dollar"))
        symboles.add(Symboles("LSL", "Lesotho Loti"))
        symboles.add(Symboles("LTL", "Lithuanian Litas"))
        symboles.add(Symboles("LVL", "Latvian Lats"))
        symboles.add(Symboles("LYD", "Libyan Dinar"))
        symboles.add(Symboles("MAD", "Moroccan Dirham"))
        symboles.add(Symboles("MDL", "Moldovan Leu"))
        symboles.add(Symboles("MGA", "Malagasy Ariary"))
        symboles.add(Symboles("MKD", "Macedonian Denar"))
        symboles.add(Symboles("MMK", "Myanma Kyat"))
        symboles.add(Symboles("MNT", "Mongolian Tugrik"))
        symboles.add(Symboles("MOP", "Macanese Pataca"))
        symboles.add(Symboles("MRO", "Mauritanian Ouguiya"))
        symboles.add(Symboles("MUR", "Mauritian Rupee"))
        symboles.add(Symboles("MVR", "Maldivian Rufiyaa"))
        symboles.add(Symboles("MWK", "Malawian Kwacha"))
        symboles.add(Symboles("MXN", "Mexican Peso"))
        symboles.add(Symboles("MYR", "Malaysian Ringgit"))
        symboles.add(Symboles("MZN", "Mozambican Metical"))
        symboles.add(Symboles("NAD", "Namibian Dollar"))
        symboles.add(Symboles("NGN", "Nigerian Naira"))
        symboles.add(Symboles("NIO", "Nicaraguan Córdoba"))
        symboles.add(Symboles("NOK", "Norwegian Krone"))
        symboles.add(Symboles("NPR", "Nepalese Rupee"))
        symboles.add(Symboles("NZD", "New Zealand Dollar"))
        symboles.add(Symboles("OMR", "Omani Rial"))
        symboles.add(Symboles("PAB", "Panamanian Balboa"))
        symboles.add(Symboles("PEN", "Peruvian Nuevo Sol"))
        symboles.add(Symboles("PGK", "Papua New Guinean Kina"))
        symboles.add(Symboles("PHP", "Philippine Peso"))
        symboles.add(Symboles("PKR", "Pakistani Rupee"))
        symboles.add(Symboles("PLN", "Polish Zloty"))
        symboles.add(Symboles("PYG", "Paraguayan Guarani"))
        symboles.add(Symboles("QAR", "Qatari Rial"))
        symboles.add(Symboles("RON", "Romanian Leu"))
        symboles.add(Symboles("RSD", "Serbian Dinar"))
        symboles.add(Symboles("RUB", "Russian Ruble"))
        symboles.add(Symboles("RWF", "Rwandan Franc"))
        symboles.add(Symboles("SAR", "Saudi Riyal"))
        symboles.add(Symboles("SBD", "Solomon Islands Dollar"))
        symboles.add(Symboles("SCR", "Seychellois Rupee"))
        symboles.add(Symboles("SDG", "Sudanese Pound"))
        symboles.add(Symboles("SEK", "Swedish Krona"))
        symboles.add(Symboles("SGD", "Singapore Dollar"))
        symboles.add(Symboles("SHP", "Saint Helena Pound"))
        symboles.add(Symboles("SLE", "Sierra Leonean Leone"))
        symboles.add(Symboles("SLL", "Sierra Leonean Leone"))
        symboles.add(Symboles("SOS", "Somali Shilling"))
        symboles.add(Symboles("SRD", "Surinamese Dollar"))
        symboles.add(Symboles("STD", "São Tomé and Príncipe Dobra"))
        symboles.add(Symboles("SVC", "Salvadoran Colón"))
        symboles.add(Symboles("SYP", "Syrian Pound"))
        symboles.add(Symboles("SZL", "Swazi Lilangeni"))
        symboles.add(Symboles("THB", "Thai Baht"))
        symboles.add(Symboles("TJS", "Tajikistani Somoni"))
        symboles.add(Symboles("TMT", "Turkmenistani Manat"))
        symboles.add(Symboles("TND", "Tunisian Dinar"))
        symboles.add(Symboles("TOP", "Tongan Paʻanga"))
        symboles.add(Symboles("TRY", "Turkish Lira"))
        symboles.add(Symboles("TTD", "Trinidad and Tobago Dollar"))
        symboles.add(Symboles("TWD", "New Taiwan Dollar"))
        symboles.add(Symboles("TZS", "Tanzanian Shilling"))
        symboles.add(Symboles("UAH", "Ukrainian Hryvnia"))
        symboles.add(Symboles("UGX", "Ugandan Shilling"))
        symboles.add(Symboles("USD", "United States Dollar"))
        symboles.add(Symboles("UYU", "Uruguayan Peso"))
        symboles.add(Symboles("UZS", "Uzbekistan Som"))
        symboles.add(Symboles("VEF", "Venezuelan Bolívar Fuerte"))
        symboles.add(Symboles("VES", "Sovereign Bolivar"))
        symboles.add(Symboles("VND", "Vietnamese Dong"))
        symboles.add(Symboles("VUV", "Vanuatu Vatu"))
        symboles.add(Symboles("WST", "Samoan Tala"))
        symboles.add(Symboles("XAF", "CFA Franc BEAC"))
        symboles.add(Symboles("XAG", "Silver (troy ounce)"))
        symboles.add(Symboles("XAU", "Gold (troy ounce)"))
        symboles.add(Symboles("XCD", "East Caribbean Dollar"))
        symboles.add(Symboles("XDR", "Special Drawing Rights"))
        symboles.add(Symboles("XOF", "CFA Franc BCEAO"))
        symboles.add(Symboles("XPF", "CFP Franc"))
        symboles.add(Symboles("YER", "Yemeni Rial"))
        symboles.add(Symboles("ZAR", "South African Rand"))
        symboles.add(Symboles("ZMK", "Zambian Kwacha (pre-2013)"))
        symboles.add(Symboles("ZMW", "Zambian Kwacha"))
        symboles.add(Symboles("ZWL", "Zimbabwean Dollar"))
        return symboles
    }
}
